[package]
name = "chess-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0"
bevy-fps-counter = "0"
bevy_kira_audio = { version = "0", features = ["mp3"] }
bevy_mod_picking = "0.12"
ordinal-type = "0"
